# Generated by Django 6.0.4 on 2026-05-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppJob', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='type',
            field=models.CharField(choices=[('DSA', 'DSA'), ('APTITUDE', 'APTITUDE')], default='DSA', max_length=50),
        ),
    ]
