# Generated by Django 6.0.4 on 2026-04-26 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppResume', '0002_userresume_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresume',
            old_name='file',
            new_name='ats_resume',
        ),
        migrations.RenameField(
            model_name='userresume',
            old_name='raw_text',
            new_name='ats_resume_raw_text',
        ),
    ]
