# Generated by Django 6.0.4 on 2026-04-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppResume', '0003_rename_file_userresume_ats_resume_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresume',
            old_name='ats_resume',
            new_name='ats_resume_file',
        ),
        migrations.AddField(
            model_name='userresume',
            name='job_details',
            field=models.TextField(blank=True),
        ),
    ]
