# Generated by Django 6.0.4 on 2026-05-07 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppResume', '0004_rename_ats_resume_userresume_ats_resume_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userresume',
            old_name='ats_resume_file',
            new_name='resume_file',
        ),
        migrations.RenameField(
            model_name='userresume',
            old_name='ats_resume_raw_text',
            new_name='resume_raw_text',
        ),
    ]
