# Generated by Django 6.0.4 on 2026-05-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppResume', '0006_remove_userresume_job_details_alter_userresume_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResume',
        ),
    ]
