# Generated by Django 6.0.4 on 2026-05-07 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume_raw_text',
            field=models.TextField(blank=True),
        ),
    ]
