# Generated by Django 6.0.4 on 2026-05-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUser', '0002_user_resume_raw_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_skills_projects',
            field=models.TextField(blank=True),
        ),
    ]
